### ISSUE TITLE
Great library!

### ISSUE THREAD

**Issue by itsjoeconway** [CurC/flood#1]
Just saw this package - really neat. Saw in the README that it wasn't clear where to use this code. In the `aqueduct_test` package, there is a hook for startup during tests that you could use this library in: https://pub.dartlang.org/documentation/aqueduct_test/latest/aqueduct_test/TestHarnessORMMixin-class.html. 

Hope this is helpful! Feel free to delete this issue, figured it was the easiest way to reach out.

**Comment by itsjoeconway** [comment]
Also, love the name - 10/10.

**Comment by crtschin** [comment]
Thanks Joe, I'll take a look at it!
